# Generated by Django 4.2.7 on 2026-01-07 07:57

from django.db import migrations


def create_default_roles_and_owners(apps, schema_editor):
    """Create default roles for existing organizations and set up owners."""
    Organization = apps.get_model('pm_app', 'Organization')
    Role = apps.get_model('pm_app', 'Role')
    User = apps.get_model('pm_app', 'User')
    
    # Default role definitions
    default_roles = {
        'Admin': {
            'description': 'Default Admin role',
            'permissions': {
                'create_project': True,
                'edit_project': True,
                'delete_project': True,
                'create_task': True,
                'edit_task': True,
                'delete_task': True,
                'assign_task': True,
                'comment_task': True,
                'manage_users': True,
                'manage_roles': True,
                'view_all': True,
            },
            'is_default': True
        },
        'Manager': {
            'description': 'Default Manager role',
            'permissions': {
                'create_project': True,
                'edit_project': True,
                'delete_project': False,
                'create_task': True,
                'edit_task': True,
                'delete_task': True,
                'assign_task': True,
                'comment_task': True,
                'manage_users': False,
                'manage_roles': False,
                'view_all': True,
            },
            'is_default': True
        },
        'Member': {
            'description': 'Default Member role',
            'permissions': {
                'create_project': False,
                'edit_project': False,
                'delete_project': False,
                'create_task': True,
                'edit_task': True,
                'delete_task': False,
                'assign_task': False,
                'comment_task': True,
                'manage_users': False,
                'manage_roles': False,
                'view_all': True,
            },
            'is_default': True
        },
        'Viewer': {
            'description': 'Default Viewer role',
            'permissions': {
                'create_project': False,
                'edit_project': False,
                'delete_project': False,
                'create_task': False,
                'edit_task': False,
                'delete_task': False,
                'assign_task': False,
                'comment_task': True,
                'manage_users': False,
                'manage_roles': False,
                'view_all': True,
            },
            'is_default': True
        }
    }
    
    for org in Organization.objects.all():
        # Create default roles for this organization
        created_roles = {}
        for role_name, role_data in default_roles.items():
            role, created = Role.objects.get_or_create(
                organization=org,
                name=role_name,
                defaults=role_data
            )
            created_roles[role_name] = role
        
        # Set the first user in the organization as owner if not set
        if not org.owner:
            first_user = User.objects.filter(organization=org).first()
            if first_user:
                org.owner = first_user
                org.save()
                # Give the owner admin role
                if not first_user.role:
                    first_user.role = created_roles.get('Admin')
                    first_user.save()
        
        # Assign Member role to users without roles
        for user in User.objects.filter(organization=org, role=None):
            user.role = created_roles.get('Member')
            user.save()


def reverse_default_roles(apps, schema_editor):
    """Remove default roles."""
    Role = apps.get_model('pm_app', 'Role')
    Role.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0002_role_remove_task_pm_app_task_assigne_271ff4_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_roles_and_owners, reverse_default_roles),
    ]
